/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import dominio.*;
import servicosTecnicos.*;

/**
 *
 * @author pc
 */
public class ViewDicionario extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    
    
    
    static ControladorSistema c;
    DefaultListModel dm = new DefaultListModel();
    
    public ViewDicionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pesquisa = new javax.swing.JInternalFrame();
        opcoesSelectLabel = new javax.swing.JLabel();
        opcoesSelect = new javax.swing.JComboBox<>();
        informacaoLabel = new javax.swing.JLabel();
        informacao = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        scrollList = new javax.swing.JScrollPane();
        listaExpressoes = new javax.swing.JList<>();
        alterarDicionarioPanel = new javax.swing.JPanel();
        selectAction = new javax.swing.JComboBox<>();
        expressaoNovaLabel = new javax.swing.JLabel();
        expressaoNova = new javax.swing.JTextField();
        expressaoAntigaLabel = new javax.swing.JLabel();
        expressaoAntiga = new javax.swing.JTextField();
        btnAvancar = new javax.swing.JButton();
        dicionarioLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dicionario = new javax.swing.JList<>();
        infoRetorno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginAdministrativoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Login = new javax.swing.JTextField();
        Senha = new javax.swing.JPasswordField();
        btnAcessar = new javax.swing.JButton();
        erroLoginLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisar");

        Pesquisa.setVisible(true);

        opcoesSelectLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opcoesSelectLabel.setText("Buscar por:");

        opcoesSelect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcoesSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Palavra na Expressão", "Expressão que começa com", "Quantidade de Palavras" }));

        informacaoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        informacaoLabel.setText("Informação:");

        informacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar.setText("Buscar");
        buscar.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                buscarComponentAdded(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Resultado da sua busca");

        listaExpressoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        scrollList.setViewportView(listaExpressoes);

        javax.swing.GroupLayout PesquisaLayout = new javax.swing.GroupLayout(Pesquisa.getContentPane());
        Pesquisa.getContentPane().setLayout(PesquisaLayout);
        PesquisaLayout.setHorizontalGroup(
            PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesquisaLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(scrollList, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
            .addGroup(PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PesquisaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(opcoesSelectLabel)
                        .addComponent(informacaoLabel))
                    .addGap(36, 36, 36)
                    .addGroup(PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(opcoesSelect, 0, 389, Short.MAX_VALUE)
                        .addComponent(informacao)
                        .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        PesquisaLayout.setVerticalGroup(
            PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesquisaLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PesquisaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opcoesSelectLabel)
                        .addComponent(opcoesSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(informacaoLabel)
                        .addComponent(informacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
        );

        selectAction.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inserir", "Alterar", "Verificar" }));
        selectAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionActionPerformed(evt);
            }
        });
        selectAction.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selectActionPropertyChange(evt);
            }
        });

        expressaoNovaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expressaoNovaLabel.setText("Expressão");

        expressaoNova.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        expressaoAntigaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expressaoAntigaLabel.setText("Expressão Antiga");

        expressaoAntiga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAvancar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        dicionarioLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dicionarioLabel.setText("Dicionário");

        jScrollPane2.setViewportView(dicionario);

        infoRetorno.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        jLabel2.setText("Selecione abaixo entre Inserir, Alterar e Verificar");

        javax.swing.GroupLayout alterarDicionarioPanelLayout = new javax.swing.GroupLayout(alterarDicionarioPanel);
        alterarDicionarioPanel.setLayout(alterarDicionarioPanelLayout);
        alterarDicionarioPanelLayout.setHorizontalGroup(
            alterarDicionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarDicionarioPanelLayout.createSequentialGroup()
                .addGroup(alterarDicionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(alterarDicionarioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(alterarDicionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dicionarioLabel)
                            .addComponent(expressaoAntigaLabel)
                            .addGroup(alterarDicionarioPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(expressaoNovaLabel)))
                        .addGroup(alterarDicionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(alterarDicionarioPanelLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(infoRetorno)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarDicionarioPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(alterarDicionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                                    .addComponent(selectAction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(expressaoNova, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(expressaoAntiga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAvancar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        alterarDicionarioPanelLayout.setVerticalGroup(
            alterarDicionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarDicionarioPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(alterarDicionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expressaoNovaLabel)
                    .addComponent(expressaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterarDicionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expressaoAntigaLabel)
                    .addComponent(expressaoAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAvancar)
                .addGap(24, 24, 24)
                .addComponent(dicionarioLabel)
                .addGap(8, 8, 8)
                .addComponent(infoRetorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        expressaoAntigaLabel.setVisible(false);
        expressaoAntiga.setVisible(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("É necessário permissão especial para acessar essa tela");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Login");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Senha");

        Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAcessar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAcessar.setText("Acessar");
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });

        erroLoginLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        erroLoginLabel1.setForeground(new java.awt.Color(255, 0, 0));
        erroLoginLabel1.setText("Erro: Login ou senha incorretos");

        javax.swing.GroupLayout loginAdministrativoPanelLayout = new javax.swing.GroupLayout(loginAdministrativoPanel);
        loginAdministrativoPanel.setLayout(loginAdministrativoPanelLayout);
        loginAdministrativoPanelLayout.setHorizontalGroup(
            loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdministrativoPanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginAdministrativoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdministrativoPanelLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(erroLoginLabel1)
                            .addGap(88, 88, 88))
                        .addGroup(loginAdministrativoPanelLayout.createSequentialGroup()
                            .addGroup(loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loginAdministrativoPanelLayout.createSequentialGroup()
                                        .addGroup(loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(21, 21, 21)
                                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)))
                            .addContainerGap()))))
        );
        loginAdministrativoPanelLayout.setVerticalGroup(
            loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdministrativoPanelLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginAdministrativoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addGap(50, 50, 50)
                    .addGroup(loginAdministrativoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addComponent(jLabel7)
                    .addGap(27, 27, 27)
                    .addComponent(btnAcessar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(erroLoginLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        erroLoginLabel1.setVisible(false);

        jMenu1.setText("Pesquisar no Dicionário");
        jMenu1.setToolTipText("");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alterar Dicionário");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alterarDicionarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Pesquisa, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(loginAdministrativoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(138, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alterarDicionarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(loginAdministrativoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(141, Short.MAX_VALUE)))
        );

        alterarDicionarioPanel.setVisible(false);
        loginAdministrativoPanel.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Pesquisa.setVisible(false);              
        if(c.isLogado()){
            loginAdministrativoPanel.setVisible(false);
            alterarDicionarioPanel.setVisible(true);
        }else{
            loginAdministrativoPanel.setVisible(true);
            alterarDicionarioPanel.setVisible(false);
        }        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Pesquisa.setVisible(true);
        alterarDicionarioPanel.setVisible(false);
        loginAdministrativoPanel.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed

        ArrayList<String> al = new ArrayList();

        /*String resultado = new metodo construtor que vai resolver das parada do alterar, inserir e verificar()*/
        String resultado = c.gerenciarAcoes(expressaoNova.getText().toString(), expressaoAntiga.getText().toString(),  selectAction.getSelectedIndex());
        infoRetorno.setText(resultado);
        infoRetorno.setForeground(Color.BLUE);

        al = c.getExpressoesDicionario();

        dicionario.setModel(dm);
        dm.clear();
        for(String nome: al){
            dm.addElement(nome);
        }
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void selectActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionActionPerformed
        System.out.println(selectAction.getSelectedItem());
        if(selectAction.getSelectedItem().equals("Alterar")){
            expressaoAntigaLabel.setVisible(true);
            expressaoAntiga.setVisible(true);
            expressaoNovaLabel.setText("Expressão Nova");

        }
        else{
            expressaoAntigaLabel.setVisible(false);
            expressaoAntiga.setVisible(false);
            expressaoAntiga.setText("");
            expressaoNovaLabel.setText("Expressão");
        }
    }//GEN-LAST:event_selectActionActionPerformed

    private void selectActionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selectActionPropertyChange

    }//GEN-LAST:event_selectActionPropertyChange

    private void buscarComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_buscarComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarComponentAdded

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        ArrayList<String> al = new ArrayList();

        al = c.buscarExpressoes(informacao.getText().toString(), opcoesSelect.getSelectedIndex());

        listaExpressoes.setModel(dm);
        dm.clear();
        dm.addElement("Buscar por: " + opcoesSelect.getSelectedItem() + " > " + informacao.getText().toString());
        for(String nome: al){
            dm.addElement(nome);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        c.loginAdmin(Login.getText(), String.valueOf(Senha.getPassword()));
        System.out.println(String.valueOf(Senha.getPassword()));
        if(c.isLogado()){
            loginAdministrativoPanel.setVisible(false);
            alterarDicionarioPanel.setVisible(true);
        }
        else{
            erroLoginLabel1.setVisible(true);
        }
    }//GEN-LAST:event_btnAcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDicionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDicionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDicionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDicionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDicionario().setVisible(true);                  
           }
        });
        
        c = new ControladorSistema();
        c.iniciarSistema();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Login;
    private javax.swing.JInternalFrame Pesquisa;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JPanel alterarDicionarioPanel;
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton buscar;
    private javax.swing.JList<String> dicionario;
    private javax.swing.JLabel dicionarioLabel;
    private javax.swing.JLabel erroLoginLabel1;
    private javax.swing.JTextField expressaoAntiga;
    private javax.swing.JLabel expressaoAntigaLabel;
    private javax.swing.JTextField expressaoNova;
    private javax.swing.JLabel expressaoNovaLabel;
    private javax.swing.JLabel infoRetorno;
    private javax.swing.JTextField informacao;
    private javax.swing.JLabel informacaoLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaExpressoes;
    private javax.swing.JPanel loginAdministrativoPanel;
    private javax.swing.JComboBox<String> opcoesSelect;
    private javax.swing.JLabel opcoesSelectLabel;
    private javax.swing.JScrollPane scrollList;
    private javax.swing.JComboBox<String> selectAction;
    // End of variables declaration//GEN-END:variables
}
